apiVersion: v1
kind: Secret
metadata:
  name: deployment-books-secrets
type: Opaque
data:
  password_rabbitmq: Q3QwYUFCSm5kNTJNMVJGelhnblFmNk1IMHhqc05zaUE=
  password_mongodb: V3NNMmxic2d3ZAo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-books
  labels:
    owner: szabodorottya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: container-books
          image: macidori98/books22:57 #35 a jo valtozat assync comm nelkul
          imagePullPolicy: Always
          env:
            - name: SECRET_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deployment-books-secrets
                  key: password_rabbitmq
            - name: SECRET_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deployment-books-secrets
                  key: password_mongodb
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-books
  labels:
    owner: szabodorottya
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: books
