apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-images
  labels:
    owner: szabodorottya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
        - name: container-images
          image: macidori98/pythonapp:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-images
  labels:
    owner: szabodorottya
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: images
